<?php

/**
 * @file
 * Custom Language Detector module.
 */

/**
 * Implements hook_menu().
 */
function custom_lang_menu() {
  $items = array();

  $items['admin/config/regional/custom_lang'] = array(
    'title' => 'Set language prefixes',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('custom_lang_settings_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/custom_lang.admin.inc',
  );
  $items['admin/config/regional/custom_lang/settings'] = array(
    'title' => 'Settings',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 0,
  );
  $items['admin/config/regional/custom_lang/test'] = array(
    'title' => 'Test with IP',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('custom_lang_ip_test_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/custom_lang.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function custom_lang_theme($existing, $type, $theme, $path) {

  return array(
    'custom_lang_tabular_form' => array(
      'render element' => 'form',
      'file' => 'includes/custom_lang.admin.inc',
    ),
  );
}

/**
 * Implements hook_block_view_alter().
 */
function custom_lang_block_view_alter(&$data, $block) {
  if ($block->module == 'lang_dropdown') {
    if (!isset($_COOKIE['Drupal_visitor_custom_lang'])) {
      $ip = ip_address();
      $ip = '31.23.193.201';
      if ($ip != '127.0.0.1') {
        module_load_include('inc', 'custom_lang', 'includes/custom_lang.helper');
        custom_lang_set_lang($ip);
      }
    }
  }
}
